spring:
  #h2:
  #  console:
  #   enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://oq9kbzjixz5wagxw:i7no59j4dm57dp97@yjo6uubt3u5c16az.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/j4piikc3givhbwow
    username: oq9kbzjixz5wagxw
    password: i7no59j4dm57dp97
  jpa:
    defer-datasource-initialization: true

server:
  port: 80