spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://bfb75e5fbdc46b:0fc64a14@us-cdbr-east-04.cleardb.com/heroku_e0450822ed6def7?reconnect=true
    username: bfb75e5fbdc46b
    password: 0fc64a14
  jpa:
    defer-datasource-initialization: true

server:
  port: 80